### PR TITLE
Update environment.yml

### PR DESCRIPTION
**Pull request by Amir-Arsalan**
Without the new version of scikit-image you'll get the following errors:
```

Testing Pipeline
==> Parsing arguments
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    opt = options_test.parse()
  File "/om/user/arsalans/GenRe-ShapeHD/options/options_test.py", line 44, in parse
    parser, _ = get_model(net_name, test=True).add_arguments(parser)
  File "/om/user/arsalans/GenRe-ShapeHD/models/__init__.py", line 5, in get_model
    module = importlib.import_module('models.' + alias)
  File "/om/user/arsalans/condaEnvs/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/om/user/arsalans/GenRe-ShapeHD/models/genre_full_model.py", line 5, in <module>
    from models.depth_pred_with_sph_inpaint import Net as Depth_inpaint_net
  File "/om/user/arsalans/GenRe-ShapeHD/models/depth_pred_with_sph_inpaint.py", line 4, in <module>
    from models.marrnet1 import Model as DepthModel
  File "/om/user/arsalans/GenRe-ShapeHD/models/marrnet1.py", line 8, in <module>
    from .marrnetbase import MarrnetBaseModel
  File "/om/user/arsalans/GenRe-ShapeHD/models/marrnetbase.py", line 6, in <module>
    from models.netinterface import NetInterface
  File "/om/user/arsalans/GenRe-ShapeHD/models/netinterface.py", line 9, in <module>
    from visualize.visualizer import Visualizer
  File "/om/user/arsalans/GenRe-ShapeHD/visualize/visualizer.py", line 8, in <module>
    from skimage import measure
  File "/om/user/arsalans/condaEnvs/lib/python3.6/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/om/user/arsalans/condaEnvs/lib/python3.6/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/om/user/arsalans/condaEnvs/lib/python3.6/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths'
```

### CODE REVIEW

**Comment by Amir-Arsalan** [comment]
@xiumingzhang relevant --> https://github.com/scikit-image/scikit-image/issues/3586

**Comment by xiumingzhang** [comment]
Thanks Amir for the PR!

Before I merge this, would you mind sharing your script that gives rise to this error so that I can reproduce it?

**Comment by Amir-Arsalan** [comment]
@xiumingzhang So I basically cloned the repo and made a conda environment with the dependencies in `environment.yml`, placed my images in `downloads/data/test/genre/` and ran the test script and got the errors above. You probably can also fix this if you make sure an older version of Numpy (e.g. 1.15) is installed but I didn't try it.

**Comment by xiumingzhang** [comment]
Merged with some edits.

Thanks Amir. I was able to reproduce this. I added a line to ensure numpy 1.15.4 (the original numpy version during our development) into the envrionment.yml. It passed my tests and sounds safer than using a newer scikit-image.

**Pull request merged**
